theme = "hugo-theme-casper"
BaseUrl = "/"
publishDir = "public/"
LanguageCode = "en-us"
Title = "JU***BAR***LY"
paginate = 5
# DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2019"
canonifyurls = true
enableEmoji = true
comments = true

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "Tags"
    url = "/tags/"

[[menu.main]]
    name = "Art and Music"
    url = "/categories/art-and-music/"

[[menu.main]]
    name = "Data Science"
    url = "/categories/data-science/"

[[menu.main]]
    name = "Miscellaneous"
    url = "/categories/miscellaneous/"

[params]
    description = "Wei-Chun Chu's Blog"
    cover = "images/sun-moon_lake.jpg"

    author = "Wei-Chun Chu"
    authorlocation = "Berlin, Germany"
    # googleAnalyticsUserID = "UA-79101-12"

    logo = "images/profile_pic_3.jpg"
    hideHUGOSupport = true

    twitterName = "weichunchu01"
    instagramName = "jubarlystudio"
    githubName = "wcchu"

    # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
    # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
    # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
    hjsStyle = "default"

[param.social]
    github  = "https://github.com/wcchu"
    twitter = "https://twitter.com/weichunchu01"
    instagram = "https://www.instagram.com/jubarlystudio"
    soundcloud = "https://soundcloud.com/wcchu"
